### ISSUE TITLE
Rename "license" subdir. to "licenses" to conform to other project repos.

### ISSUE THREAD

**Issue by mrutkows** [apache/incubator-openwhisk-runtime-swift#52]
This may have been a typo/mix-up, but this repo. placed all referenced license files into a subdir named "license" singular; it should be plural or "licenses" to conform to what we do in all other repos.

**Comment by daisy-ycguo** [comment]
I think this can be closed since we have removed all license files.

**Comment by mrutkows** [comment]
This issue is now being tracked in the release repo. here: https://github.com/apache/incubator-openwhisk-release/issues/170
