### ISSUE TITLE
What is the license of ibmcom/swift-ubuntu:3.1.1

### ISSUE THREAD

**Issue by houshengbo** [apache/incubator-openwhisk-runtime-swift#53]
https://hub.docker.com/r/ibmcom/swift-ubuntu-runtime/

We use this image, but we are not sure of the license.

**Comment by seabaylea** [comment]
That image is build via the following project:
    https://github.com/IBM-Swift/swift-ubuntu-docker
The project has an Apache 2.0 license. The Swift toolchain itself is license under Apache 2.0 with a Runtime Library Exception:
    https://swift.org/LICENSE.txt

**Comment by houshengbo** [comment]
Good, then I do not need to worry about the license
Thanks.
