### ISSUE TITLE
Swift 3.1.1 runtime fails for large input

### ISSUE THREAD

**Issue by rabbah** [apache/incubator-openwhisk-runtime-swift#74]
the Swift 4.0 runtime passes the large input test but not the 3.1.1 test.

https://github.com/apache/incubator-openwhisk-runtime-swift/blob/4432bfb0c5cf817119ee88ba6108e7c97e13a331/tests/src/test/scala/runtime/actionContainers/Swift311ActionContainerTests.scala#L31

@eweiter is this something you can help with?

**Comment by eweiter** [comment]
@rabbah Yes, I will look into it. 
Is this critical where I need to get to it today or what is the priority of it?

**Comment by rabbah** [comment]
That’s great thanks. I bypassed the test for the time being. When you can get to it...

**Comment by csantanapr** [comment]
Closing as wontFix, for large inputs user will need to use Swift 4 runtime, which the epilogue will handle the input in stdin.
For swift 3 the input remains as env variable.
