### ISSUE TITLE
Async Swift Action and Promise/Future

### ISSUE THREAD

**Issue by markusthoemmes** [apache/incubator-openwhisk-runtime-swift#76]
@JacopoMangiavacchi commented on [Thu Apr 07 2016](https://github.com/apache/incubator-openwhisk/issues/193)

Current Swift support is limited to synchronous action.  It should be nice to support GCD queue capabilities and implement a Whisk Swift API based on Promise/Future pattern such as BrightFutures https://github.com/Thomvis/BrightFutures

**Comment by csantanapr** [comment]
Async Swift is now possible by using Swift 4.1 and completion handler.
