### ISSUE TITLE
Provide Swift 4.2 runtime 🚀

### ISSUE THREAD

**Issue by jthomas** [apache/incubator-openwhisk-runtime-swift#83]
User asked about this [recently](https://github.com/serverless/serverless-openwhisk/issues/135)...

Swift 4.2 has now been released.
https://www.hackingwithswift.com/articles/77/whats-new-in-swift-4-2

**Comment by chrislonge** [comment]
[Swift 4.2 Released](https://swift.org/blog/swift-4-2-released/) 🎉

**Comment by csantanapr** [comment]
Now that Swift 4.2 is released, we can move forward with implementing support.
@sciabarracom is looking into using the new actionloop to make swift 4.2 stateful, meaning the swift application will not exit with every invocation/run, it will read from stdin every invocation input params including env variables.

From an user perspective, no braking changes they can migrate their swift 4.1 actions to 4.2 just by recompiling and using the new epilogue based on actionloop
https://github.com/apache/incubator-openwhisk-runtime-go/tree/master/actionProxyLoop

**Comment by rabbah** [comment]
is this issue still relevant?

**Comment by csantanapr** [comment]
This is done
